# Generated by Django 5.2.7 on 2025-10-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_advuser_fio_advuser_patronymic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название категории', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='advuser',
            name='is_activated',
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Название')),
                ('description', models.TextField(help_text='Описание', max_length=1000)),
                ('photo', models.FileField(upload_to='uploads/')),
                ('status', models.CharField(blank=True, choices=[('n', 'Новая'), ('o', 'Принята в работу'), ('d', 'Выполнена')], default='n', help_text='Статус заявки', max_length=1)),
                ('categories', models.ManyToManyField(help_text='Выберите категорию', to='catalog.categories')),
            ],
        ),
    ]
