# Generated by Django 5.2.7 on 2025-10-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_categories_remove_advuser_is_activated_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='application',
            name='photo',
            field=models.FileField(upload_to='photos/'),
        ),
    ]
