# Generated by Django 5.2.7 on 2025-10-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_advuser_user_application_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advuser',
            name='user',
        ),
        migrations.AddField(
            model_name='application',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
